<a href="https://colab.research.google.com/github/rachanabramhane/assignment/blob/main/Tamil_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install spacy
!python -m spacy download en_core_web_sm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
2022-08-18 06:06:34.368737: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 12.8 MB 12.6 MB/s 
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [ ]:
#data link = https://raw.githubusercontent.com/laxmimerit/NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset/master/datasets/imdb_labelled.txt

In [ ]:
import spacy

In [ ]:
spacy.load('en_core_web_sm')

In [ ]:
import en_core_web_sm
nlp = en_core_web_sm.load()

In [ ]:
x = 'king and women'
doc = nlp(x)

for token1 in doc:
  for token2 in doc:
    print(token1.text, token2.text, token1.similarity(token2))

king king 1.0
king and -0.04387429729104042
king women 0.2168489545583725
and king -0.04387429729104042
and and 1.0
and women -0.047409459948539734
women king 0.2168489545583725
women and -0.047409459948539734
women women 1.0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  


In [ ]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Tamil_first_ready_for_sentiment.csv', sep = '\t')


In [ ]:
df.head()

Negative                Enna da ellam avan seyal  Mari iruku
0  Negative           This movei is just like  ellam avan seyal
1  Positive    Padam vanthathum 13k dislike pottavaga yellam...
2  Positive     Neraya neraya neraya... ... V era level...thala
3  Positive    wow thavala sema mass....padam oru pundaikum ...
4  Negative    Andha 19 k unlike panavangaluku kolandha pora...

In [ ]:
#another dataset link= 'https://raw.githubusercontent.com/laxmimerit/NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset/master/datasets/imdb_labelled.txt', sep = '\t')

In [ ]:
df.head()

A very, very, very slow-moving, aimless movie about a distressed, drifting young man.    \
0  Not sure who was more lost - the flat characte...                                        
1  Attempting artiness with black & white and cle...                                        
2       Very little music or anything to speak of.                                          
3  The best scene in the movie was when Gerardo i...                                        
4  The rest of the movie lacks art, charm, meanin...                                        

   0  
0  0  
1  0  
2  0  
3  1  
4  0

In [ ]:
!pip install git+https://github.com/laxmimerit/preprocess_kgptalkie.git --upgrade --force-reinstall

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/laxmimerit/preprocess_kgptalkie.git to /tmp/pip-req-build-fhz1z_sp
  Running command git clone -q https://github.com/laxmimerit/preprocess_kgptalkie.git /tmp/pip-req-build-fhz1z_sp
  Created wheel for preprocess-kgptalkie: filename=preprocess_kgptalkie-0.1.3-py3-none-any.whl size=11756 sha256=2d416a8e98d4599b91cb934a5884101514e9b55715324b87b69df25ccae562cd
  Stored in directory: /tmp/pip-ephem-wheel-cache-dzr6524i/wheels/0d/b3/29/bfe3deffda68980088d17b81331be6667e837ffb4a071bae82
Successfully built preprocess-kgptalkie
  Attempting uninstall: preprocess-kgptalkie
    Found existing installation: preprocess-kgptalkie 0.1.3
    Uninstalling preprocess-kgptalkie-0.1.3:
      Successfully uninstalled preprocess-kgptalkie-0.1.3


In [ ]:
def get_clean(x):
    x = str(x).lower().replace('\\', '').replace('_', ' ')
    x = ps.cont_exp(x)
    x = ps.remove_emails(x)
    x = ps.remove_urls(x)
    x = ps.remove_html_tags(x)
    x = ps.remove_rt(x)
    x = ps.remove_accented_chars(x)
    x = ps.remove_special_chars(x)
    x = re.sub("(.)\\1{2,}", "\\1", x)
    return x

In [ ]:
import preprocess_kgptalkie as ps
import re

In [ ]:
x = ' you have #@$text DaTa this youuu@#$$%!'
get_clean(x)

'you have text data this you'

In [ ]:
# build a model

**word2vect conversion**

In [ ]:
x = 'cat dog'
doc = nlp(x)

In [ ]:
doc.vector

array([ 1.1019777 ,  0.14818648, -0.01898211, -0.80369985,  0.08938813,
        0.23038155,  0.14141321, -0.28826585,  1.1105285 , -0.21451718,
       -0.02473798,  0.24901688,  0.5550181 ,  0.11733441, -0.5894057 ,
       -0.5164957 , -0.32763553,  0.64845705, -0.20707141, -0.3771626 ,
       -0.10344088, -0.11728874, -0.3227778 ,  0.33523053,  0.8882291 ,
        0.7558304 ,  0.25621855, -0.37717468,  0.8112372 ,  0.3868908 ,
       -0.08903962,  0.30966955, -0.98485166, -0.07335573,  0.70130867,
        0.30843467, -0.31750193,  0.37322208, -0.8138824 , -0.4488434 ,
       -0.13713332,  0.22188771, -0.15347701, -1.47674   , -0.29649734,
       -0.7168839 ,  1.0800779 ,  1.1572498 , -0.10057739, -0.45597315,
       -0.05254351, -0.8069477 , -0.80664253, -1.9219813 , -0.8609656 ,
        0.2307784 ,  0.87619764, -0.57367605, -0.5535555 , -0.2150563 ,
       -1.1963638 , -0.40919322,  0.11361595, -0.8790451 ,  0.02309138,
       -0.17116418,  0.04251403,  0.6183914 , -0.24352193, -1.40

In [ ]:
doc.vector.shape

(96,)

In [ ]:
doc[0].vector

array([ 1.7594774 , -0.21249838, -0.07283511, -0.38783666, -0.40762526,
       -0.50578505,  0.12791802, -0.00897793,  0.81911683, -0.24771652,
       -0.01195568,  0.7526125 ,  0.30068526, -0.16170707, -1.018452  ,
       -0.8081006 , -0.42618555,  0.6606422 , -0.19970733, -0.76895356,
       -0.11284542, -0.90188694, -0.34016317, -0.5244268 ,  0.84539306,
        1.4087713 ,  0.03821059, -0.6331823 ,  1.0967718 ,  0.10206433,
       -0.02582902,  0.5105456 , -0.7810317 ,  0.09342709,  2.5042057 ,
        0.4088996 , -0.04502058,  0.91588   , -1.7036713 , -0.15352118,
        0.08699146,  0.02018841,  0.5508247 , -1.6545055 ,  0.04353881,
       -0.19055673,  0.84127796,  1.2886474 ,  0.08732502, -1.2700689 ,
        0.12960443, -1.1515026 , -0.6139205 , -1.7397337 , -0.39420992,
        1.5388138 ,  2.7600317 , -0.26083925, -0.6235062 , -0.6040242 ,
       -1.4826738 , -0.6059339 ,  0.16665179, -1.1297116 ,  1.013392  ,
        0.13089502,  0.09634987,  0.321896  , -0.39680216, -1.10

In [ ]:
doc[1].vector

array([ 0.44447798,  0.5088713 ,  0.03487089, -1.219563  ,  0.5864015 ,
        0.96654814,  0.1549084 , -0.56755376,  1.4019401 , -0.18131785,
       -0.03752029, -0.2545787 ,  0.809351  ,  0.3963759 , -0.16035938,
       -0.22489077, -0.2290855 ,  0.63627195, -0.21443549,  0.01462835,
       -0.09403633,  0.66730946, -0.3053924 ,  1.1948879 ,  0.9310651 ,
        0.10288954,  0.47422653, -0.12116704,  0.52570254,  0.6717173 ,
       -0.15225023,  0.1087935 , -1.1886716 , -0.24013856, -1.1015884 ,
        0.20796975, -0.5899833 , -0.16943587,  0.07590654, -0.7441656 ,
       -0.3612581 ,  0.42358702, -0.8577787 , -1.2989745 , -0.6365335 ,
       -1.243211  ,  1.3188777 ,  1.0258522 , -0.2884798 ,  0.3581226 ,
       -0.23469144, -0.46239278, -0.99936455, -2.104229  , -1.3277214 ,
       -1.077257  , -1.0076364 , -0.8865129 , -0.48360485,  0.17391157,
       -0.91005385, -0.21245253,  0.06058012, -0.6283786 , -0.9672092 ,
       -0.4732234 , -0.0113218 ,  0.91488683, -0.0902417 , -1.71

In [ ]:
def get_vec(x):
  doc = nlp(x)
  vec = doc.vector
  return vec

In [ ]:
get_vec(x)

array([ 1.1019777 ,  0.14818648, -0.01898211, -0.80369985,  0.08938813,
        0.23038155,  0.14141321, -0.28826585,  1.1105285 , -0.21451718,
       -0.02473798,  0.24901688,  0.5550181 ,  0.11733441, -0.5894057 ,
       -0.5164957 , -0.32763553,  0.64845705, -0.20707141, -0.3771626 ,
       -0.10344088, -0.11728874, -0.3227778 ,  0.33523053,  0.8882291 ,
        0.7558304 ,  0.25621855, -0.37717468,  0.8112372 ,  0.3868908 ,
       -0.08903962,  0.30966955, -0.98485166, -0.07335573,  0.70130867,
        0.30843467, -0.31750193,  0.37322208, -0.8138824 , -0.4488434 ,
       -0.13713332,  0.22188771, -0.15347701, -1.47674   , -0.29649734,
       -0.7168839 ,  1.0800779 ,  1.1572498 , -0.10057739, -0.45597315,
       -0.05254351, -0.8069477 , -0.80664253, -1.9219813 , -0.8609656 ,
        0.2307784 ,  0.87619764, -0.57367605, -0.5535555 , -0.2150563 ,
       -1.1963638 , -0.40919322,  0.11361595, -0.8790451 ,  0.02309138,
       -0.17116418,  0.04251403,  0.6183914 , -0.24352193, -1.40

In [ ]:
df.head()

Negative                Enna da ellam avan seyal  Mari iruku
0  Negative           This movei is just like  ellam avan seyal
1  Positive    Padam vanthathum 13k dislike pottavaga yellam...
2  Positive     Neraya neraya neraya... ... V era level...thala
3  Positive    wow thavala sema mass....padam oru pundaikum ...
4  Negative    Andha 19 k unlike panavangaluku kolandha pora...

In [ ]:
df['vec'] = df['Negative'].apply(lambda x: get_vec(x))

KeyError: ignored

In [ ]:
X = df['vec'].to_numpy()
X = X.reshape(-1, 1)

KeyError: ignored